language: node_js
node_js:
  - 10

cache: npm

before_script:
  - 'git config --global url."https://github.com/".insteadOf git@github.com:'
  - 'git config --global url."https://".insteadOf git://'
  - "echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p"

script:
  - npm run build
  - npm test
